### ISSUE TITLE
What was your experience like as a manager?

### ISSUE THREAD

**Issue by mikeplis** [benmvp/ama#12]
At React Boston, you mentioned that you're transitioning back to an individual contributor role from a manager role and I was wondering if you could talk more about your experience as a manager.

Did you enjoy the experience? Why did you choose to move back to an individual contributor role? What advice would you give someone considering moving into a manager role at some point in their career?

Thanks!

**Comment by benmvp** [comment]
Sure!

So I was a manager for 2 different team for a total of just under year.

The first team was the Frontend Platform team and I only managed two people (both senior) so the people management was pretty light. I would say I coded close to 50% of the time, but it started to be less and less as I focused more on project planning and communicating with other teams.

The second team was our Destination team focused on features across Web, iOS & Android to make browsing for events more enjoyable. This was a more traditional management role. Although I only had 3 direct reports, the team itself had 8 engineers and 5 designers. So most of my time was actually spent project planning & project maintenance.

The management experience was ok. From all accounts I did pretty well. And I'm pretty sure if I continued on and got passed the initial "manager hump," I would've enjoyed it more. But I really missed being an individual contributor. And I feel that I'm still in a point where my technical contributions are greater than my people contributions. 

I still want to go around giving technical talks like I did at React Boston, I still want to review a lot of code, I still want to be in frontend technical architecture meetings, and of course I still wanted to code. The problem is that I would be a poor manager if I spent significant time doing one of those things, let alone all 4. I do like to do manager-y things like help people grow and effect process change, but I _think_ I'll still be able to do that to a degree as a technical lead.

Now that I've spent way too much time talking about myself, the best advice I can give you is all from this blog post: http://firstround.com/review/this-90-day-plan-turns-engineers-into-remarkable-managers/. I would read that and see how much resonates with you, especially the beginning parts.

Hope that helps!
