### ISSUE TITLE
PureComponent - need to know and when to use

### ISSUE THREAD

**Issue by amy-butz** [benmvp/ama#15]
I recently attended your React Workshop at Strange Loop, thanks again. I am still relatively new to React, but the use of PureComponent was something I have never encountered. I've done some Googling to understand it better, but I am finding really mixed reviews.

Do you have any suggested resources I could read, or could you briefly explain when/how to use PureComponent, why it's beneficial, and when it might not be a good idea?

Thanks!

**Comment by benmvp** [comment]
Hi Amy!

Thanks for attending the workshop!

So extending `React.PureComponent` to create a React component is basically a performance optimization. The docs for `React.PureComponent` kind of explain it: https://reactjs.org/docs/react-api.html#reactpurecomponent. This article from @treyhuffine also gives more commentary about it: https://medium.com/gitconnected/optimize-react-performance-c1a491ed9c36#63a1. The way I see it, if you do React the "right way" then you should be ok using `React.PureComponent`. 

Let's say you were keeping a deeply nested object in `state`. If you updated some portion of the object by first cloning the whole object (typically w/ the spread operator), made your changes, and then called `setState`, using `React.PureComponent` would be perfectly fine. This is the "right way" because you created a new object when any part of the object changed.

If instead you updated the object by just mutating it and then calling `setState`, `React.PureComponent` would not work because it would not call `render()`. This is because although you changed the object, the reference to the object remained the same. `React.PureComponent` just compares if the reference before the `setState` is the same as it is afterwards. If they are the same, it doesn't call `render()`. However, regular `React.Component` will go ahead and call `render()` with each call to `setState`.

So the benefit of `React.PureComponent` is that you'll be able to save some unnecessary calls to `render()` if the component's `props` & `state` don't actually change.

Does that help? What sort of info have you been reading?

**Comment by treyhuffine** [comment]
Great explanation @benmvp and thanks for the shout out! As Ben pointed out, explicitly passing the properties you need as opposed to passing an `object` to your component is almost always the best way to handle it. If you feel like passing an `object` is your only solution, then I would suggest using immutable data so that changes are recognized.

**Comment by stanleyfestus** [comment]
Explanation is excellent. Very very straightforward and easy to understand. I have wondered myself what all these buzz are all about. Now I know.
