### ISSUE TITLE
Moving an existing project to ES6

### ISSUE THREAD

**Issue by jacknehme** [benmvp/ama#16]
Hi Ben,
I attended the React demo and talk you gave at Sabio.la in January 2018.

At work we use Angular.js for the front-end and ASP.Net for the back-end. 
We build an internal web app which needs to work with IE 11, the company standard browser.
The code is written in ES5 but I'd like to move to ES6 to take advantage of the new syntax and to keep relevant in the job market. 
I got the OK from the lead front-end developer to look into the difficulty of migrating to ES6.

- What advice can you give for migrating an existing project?
- Any pitfalls we should lookout for?
- What tools would we need?
- Any other things we should be aware of or need to consider.

Thank you in advance for your time. 
-Jack

**Comment by benmvp** [comment]
Hey Jack!

Glad to hear you migrating to latest JavaScript! It's actually starting to make less sense to specify _just_ ES6/ES2015, because ES2016, ES2017 & ES2018 have also come out. And they all have some fun features in them.

My advice would be to first hook up transpilation into your build process. I'm not sure what your pipeline looks like now, but you pretty much have 2 options: [TypeScript](https://www.typescriptlang.org/) and [Babel](https://babeljs.io/). Since you're using ASP.Net and Angular, I would suggest TypeScript, but I've exclusively used Babel.

Once you have the build process hooked up, I suggest you transpile files one at a time. The nice thing is that JavaScript is fully backwards-compatible so you don't have to migrate everything at once. I suggest in any given file migrating features one by one. So if you want to start using [arrow functions](http://www.benmvp.com/learning-es6-arrow-functions/), change all of the functions in the file to arrow functions so things are consistent.

One thing you should avoid is doing a search and replace of `var` for `let`/`const`. 99% of the time, it'll be fine, but there may be cases where you're accidentally leveraging the "variable hoisting" nature of `var`.

Lastly, JavaScript goes through a yearly [proposal process](https://github.com/tc39/proposals/) so there are Stage 4 (finished), Stage 3 (candidate for next year's release), Stage 2 (draft), Stage 1 (initial proposal) & Stage 0 (strawman). I suggest you only include Stage 3 or higher. Stage 2 and below are likely to change so you'd have to update your code. Stage 3 and Stage 4 should be pretty safe to use before they are part of the official spec.

Good luck! Lemme know how it goes!

**Comment by jacknehme** [comment]
Ben, thanks for your advice. 
I've started looking into Typescript. Let's see how it goes...
