### ISSUE TITLE
How do data science, web development, and financial advising relate to the glory of God? 

### ISSUE THREAD

**Issue by Gluke92** [benmvp/ama#17]
Hi Ben,

First, I'm so grateful to God reading your website. I haven't found too many developers who are as open as you are about knowing and loving Jesus — and judging by the links to DG, I'm hopeful that you're one who's passionate about joy in the big-God of the Bible! 

Second, I would love prayer and any useful resources you have on thinking about how to go through the process of start-ups for the glory of God, and how to brainstorm on relevant services to help others with. I was a seminary student at John Piper's school, and I'm graduating this May, and retraining as a developer because God convicted me of a lack of love for my parents through Mark 7, and to get my personal finances in order. As I've been training, God's been bringing my attention to data science, web development, and personal finances, and I've been thinking more seriously about financial stewardship through a start-up I'm interning at. 

So here's the question: do you know any resources for how to think in a Christ-exalting way about using data science, web development, and financial advising for the glory of God? Or any people I could get in contact with to think about those things? Books, articles, people on the topics of God and business, and God and finances, and God and tech, would be welcome. Thank you!

**Comment by benmvp** [comment]
Hi 👋 !

Sorry for taking soooo long to respond. It was a busy week and I wanted to make sure I took the time to respond thoughtfully. I appreciate all of your kinds words. I know 100% that I wouldn't be where I am with His direction, so I always try to give Him glory whenever possible.

Congrats on your coming graduation! That must be an amazing accomplishment!

So I too have been thinking about how I can use my dev skills to bring God glory. I wouldn't say I have all the answers, but I do have some thoughts.

The first and obvious path would be to do data science, web development or financial advising for your local church. The second would be to join a Christian organization and do the same. My friend @kevinold works for LIfeWay. In either way you're clearly working for a group that's trying to advance His kingdom.

Personally, I've felt called to stay in the "marketplace," in the normal companies. In many cases, I may be the only "Jesus" they'll ever meet since they go to church. I feel like we need Christians in all areas of secular life. This Friday there's a [Work as Workshop](https://www.workasworshipretreat.org/) local church retreat to discuss how to connect our faith and work together.

Lastly, you just missed it but there was [Code for the Kingdom Nashville](http://www.codeforthekingdomnashville.org/) that just took place last weekend. There are [similar events](https://www.meetup.com/Seattle-Christian-Technologists-and-Entrepreneurs/events/247774943/) that take place around the country.

Unfortunately I don't have any books or articles that I can point you towards. At least nothing I can think of right now. But let me know if you find any!

Hope that helps!
