### ISSUE TITLE
When not to keep data in redux store

### ISSUE THREAD

**Issue by sht5** [benmvp/ama#22]
Hey Ben,
I'm working on a part of my app that will provide with some reports, basically data driven charts with some filtering.There will be many types of preset reports with different types of charts and obviously different types of data and backend queries. 
My question is, as the data structures change and there many variations, it seems weird to save every report's data as a different part of my state, should i keep it in the redux store at all? Or just in the report components local state? 
Thanks

**Comment by benmvp** [comment]
So like everything, it depends. 😃

If you're getting each of the preset reports from the backend and not doing client-side data manipulation (filtering, adding, removing, etc.) then it's probably not worth using redux at all. Basically at that point you'd be using Redux as a overly complex global data store so that multiple components could have access to the same data. You can use new [React context](https://reactjs.org/docs/context.html) for that.

However, if you're getting raw data from the backend, and then doing all the processing on the client-side, Redux would be a good option. Especially if multiple components will be triggering the client side updates. For instance, if your "presets" are just pre-determined sorts or filters on the client.

IMO, Redux is a good solution if you've got data that's gonna change over time and from multiple sources. The result is that your reducers handle more than one action, and you have more than one component firing any given action. When there's 1 component, firing one action, that's handled by one reducer, there's less value.

Of course there's always alternatives to Redux even in the situation I mentioned, but that's the use case Redux is best at handling.
