### ISSUE TITLE
Being a Christian

### ISSUE THREAD

**Issue by conradbeach** [benmvp/ama#4]
Can you tell me more about how you came to be a Christian and why you choose to be so open about it? I think it's awesome.

**Comment by benmvp** [comment]
Hey @conradbeach! Thanks! 😄 

I grew up going to church all my life so Christianity has always been a part of my life. However, I never had a personal relationship with Jesus when I was kid. Church was just another thing I did like going to school or playing basketball.

Fast forward to a year out of college I finally decided to have that personal relationship. On paper, I was living the dream. Graduated from Stanford, had a good-paying dev job, having fun partying with my roommates, etc. Don't get me wrong, it was definitely fun, but wasn't satisfied. So I made a deal with God that I'd go all in for a few months and if it being a "true Christian" was "lame" like I thought it'd be, I'd return to my lukewarm Christianity.

Well that was 10 years ago and I haven't even thought about going back. There was definitely lots I had to give up, but I got 10x more in return. I'm able to travel the world to speak about what I love to do because following/obeying Jesus put me in a place where I'd have the opportunities.

-----

So the first reason why I'm so open about is out of thankfulness. I promised God that if I ever had the opportunity to speak that I'd be bold to be open, even though on the inside I'm nervous about it each and every time. 

Secondly, me being open about it encourages other Christians in tech that it's ok to be open about it as well. I had someone at ReactConf come up to me thanking me for "making being a Christian cool". Whoa! I first heard [Eljiah Manor](https://twitter.com/elijahmanor) be open and he totally encouraged me. I want to pass that along.

Lastly there are number of Bible verses that talk about us being open about our faith, [Romans 1:16](https://www.bible.com/bible/116/ROM.1.16), [Matthew 10:32-33](https://www.bible.com/116/MAT.10.32-33), [1 Peter 3:15](https://www.bible.com/bible/116/1PE.3.15), and many more I'm sure.

-----

Well that was a lot more long-winded than I intended, but hopefully it (thoroughly) answered your question! haha

**Comment by conradbeach** [comment]
Thanks for sharing your story. That's great. I appreciate seeing your openness. I'm a committed Christian as well, but I'm often more hesitant to share that with others than I should be. We should be sharing our faith with others when given the opportunity though. That's definitely what Christ asked us to do.

**Comment by benmvp** [comment]
I definitely know how you feel. I'm actually the same way. Somehow it's easier for me to broadcast to hundreds than have a convo with a single person. The opportunity is there, but I let it slip away. We'll both do better. Deal? 😄

**Comment by conradbeach** [comment]
Haha. Deal.

**Comment by Sammuel09** [comment]
Hi Ben. Hi Conrad. Thanks for this conversation. It definitely blessed me. I am committed christian as well. Thank you.
