### ISSUE TITLE
Fluent conference 2017 Slides

### ISSUE THREAD

**Issue by alon1980** [benmvp/ama#9]
Hi Ben,
Any chance you can share that amazing presentation you did over at the conference?
In any case, even if not, can you please share with which platform have you built it so it will be interactive as it was ?

Best!

**Comment by benmvp** [comment]
Hi @alon1980!

Thanks for the kind words! You can find the slides for _Flexing your Flexbox muscles 💪_ from Fluent 2017 here: http://bit.ly/fluent-flexbox,

I used the [reveal.js](https://github.com/hakimel/reveal.js) HTML presentation framework for my slides. Since it's just HTML, CSS & JavaScript, I can do all web interactivity. I host the slides using Google Pages in my [slides repo](https://github.com/benmvp/slides).

If you don't wanna host yourself you can use [slides.com](https://slides.com/) which is a paid hosting service built using the framework and a WYSIWYG editor.
